title: "SolarWAVE Action"
description: "Advancing distributed solar ownership rights through data analysis, education, and advocacy."

url: "https://solarwave-action.github.io"
baseurl: "/solarwave-website"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin    : "aqua"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

permalink: /:categories/:title/

collections:
  publications:
    output: true
    permalink: /:collection/:name/

#lsi: false
#safe: true
##source: "solarwave-website"
#incremental: false
#highlighter: rouge
#gist:
#  noscript: false
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge

## Logo
#logo: "/assets/images/SolarWAVEActionLogoSmall.png"
#
## Search
#search_enabled: true
#
## Navigation structure
#nav_sort: case_insensitive
#
## Footer content
#footer_content: "© 2026 SolarWAVE Action | All Rights Reserved"

## Default layouts
#defaults:
#  - scope:
#      path: ""
#      type: "publications"
#    values:
#      layout: "default"
